services:
    jellyseerr:
       image: ghcr.io/seerr-team/seerr:latest
       container_name: Seerr
       environment:
          - LOG_LEVEL=debug
          - TZ=Europe/London
       ports:
          - 5055:5055
       volumes:
          - /srv/jellyseerr/config:/app/config
       healthcheck:
          test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
          start_period: 20s
          timeout: 3s
          interval: 15s
          retries: 3
       restart: unless-stopped
       network_mode: "host"
